# Generated by Django 3.2.16 on 2022-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companyname',
            field=models.TextField(blank=True, default='my company', max_length=100, verbose_name='company name'),
        ),
    ]
