# Generated by Django 3.2.16 on 2022-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='companyname',
            field=models.TextField(blank=True, default='my company', max_length=100, verbose_name='companyname'),
        ),
    ]
